#!/bin/bash

usage()
{
cat << EOF
usage: $0 options

This script run the test1 or test2 over a machine.

OPTIONS:
   -h      Show this message
   -a      ISO architecture, should be 'i386' or 'amd64'
   -f      'cinnamon','gnome','lxde','kde','nox','rqt','xfce','xorg'
   -r      release: '', 'firestarter','paintitblack','thunderstruck'
EOF
}


if [ -f ./liso.conf ]; then  
    . ./liso.conf
elif [ -f ./etc/liso.conf ]; then
    . /etc/liso.conf
else
    IsoPath=/srv/iso
    PublishingPath=/srv/iso-publisher

    # hold the three newes builds, delete older ones
    DeleteOldPublishedIsos=4

    IsoFlavour=nox
    IsoArch=amd64
    SpicePort=6666
    IsoRelease=paintitblack
    SMP=2
fi

while getopts “f:a:r:h:” OPTION; do
     case $OPTION in
         f)
             IsoFlavour=$OPTARG
             ;;
         a)
             IsoArch=$OPTARG
             ;;
         r)
             IsoRelease=$OPTARG
             ;;
         ?,h)
             usage
             exit
             ;;
     esac
done

if [ -z $IsoFlavour ] || [ -z $IsoArch ]; then
     usage
     exit 1
fi

SearchIsoDir="${PublishingPath}/${IsoRelease}/${IsoFlavour}/${IsoArch}*"
IsoDir=$(ls -d $SearchIsoDir | tail -n1)
IsoFile=$(ls ${IsoDir}/*iso | tail -n1)

if [ "x$IsoFile" == "x" ]; then
    echo ""
    echo "================================================"
    echo "Isofile with Searchpattern $SearchIso not found!"
    echo "eventually you would like one of these images:  "
    echo ""
    ls -d ${PublishingPath}/${IsoRelease}/${IsoFlavour}/${IsoArch}*
    echo ""
    exit 1
fi

IsoName=$(basename ${IsoFile%.*})
IsoVersion=$(echo $IsoName | awk -F '-' '{ print  $2 }')  # 13.1.1
IsoRelease=$(echo $IsoName | awk -F '-' '{ print  $3 }')  # paintitblack
IsoDateTime=$(echo ${IsoName} | awk -F '-' '{ print  $(NF) }' | sed "s/\([0-9]\{4\}\)\([0-9]\{2\}\)\([0-9]\{2\}\)\([0-9]\{2\}\)/\1-\2-\3_\4-/1" ) # datetime

echo ""
echo ""
echo "=============================="
echo "Delete publlished Iso:        "
echo "=============================="
echo "Iso-Version:  ${IsoVersion}"
echo "Iso-Flavour:  ${IsoFlavour}"
echo "Architecture: ${IsoArch}   "
echo "Release:      ${IsoRelease}"
echo "Date/Time:    ${IsoDateTime}"
echo ""

rm -rv  ${IsoDir}

echo ""


#ToDo Cleanup
# push the files
echo "=============================="
echo "push  $IsoRelease $IsoFlavour $IsoArch"
echo "=============================="
ssh  webdevel@test.siduction.org mkdir -p /var/www/virtual/webdevelopment/iso/siduction/${IsoRelease}/${IsoFlavour}
rsync -avd --delete /srv/iso-publisher/${IsoRelease}/${IsoFlavour}/${IsoArch}* \
     webdevel@test.siduction.org:/var/www/virtual/webdevelopment/iso/siduction/${IsoRelease}/${IsoFlavour}
echo "" 

