#!/bin/bash


rsync -v newdev:/etc/isobuilder/isobuilder.conf etc/isobuilder
rsync -v newdev:/usr/bin/kvmstart               bin
rsync -v newdev:/usr/bin/ldeliso                bin
rsync -v newdev:/usr/bin/listbuildedisos        bin
rsync -v newdev:/usr/bin/listpublishedisos      bin
rsync -v newdev:/usr/bin/lpublishiso            bin
rsync -v newdev:/usr/bin/lspiceiso              bin
rsync -v newdev:/usr/bin/lspiceuefi             bin
rsync -v newdev:/usr/bin/lunpubiso              bin
rsync -v newdev:/usr/bin/syncallpublished       bin

